# This script perform validation analysis comparting mortality cases and rates (not standarized)
# To bechnmark sources by sex for ages 20+

# Model outputs

# Generated by 06_run_scenarios.R (parallel execution for Indonesia)
out_model_path <- paste0(wd_outp, "out_model/")
files <- list.files(path = out_model_path, pattern = "\\.rds$", full.names = TRUE)

data.out <- rbindlist(
  lapply(files, function(f) { dt <- readRDS(f); setDT(dt); dt }),
  use.names = TRUE, fill = TRUE
)
data.out <- data.out[!is.na(location)]

# Filter only business as usual scenario
data.out_bau <- data.out[intervention %in% c("baseline") & scenario %in% c("baseline"),]

# 1 Comparing model estimates 2017-2050 by cause vs gbd 1990-2023

# Gbd
dt_gbd  <- readRDS(file = paste0(wd_raw,"GBD/","temp_1baseline_rates_gbd23.rds"))

#2 All cause mortality (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050

dt_unwpp_male <- C:\Users\wrgar\OneDrive - UW\02Work\WorldBank-Indonesia\uw-wb-indonesia-ncd\data\raw\unwpp\WPP2024_MORT_F01_2_DEATHS_SINGLE_AGE_MALE.xlsx

dt_unwpp_female <- C:\Users\wrgar\OneDrive - UW\02Work\WorldBank-Indonesia\uw-wb-indonesia-ncd\data\raw\unwpp\WPP2024_MORT_F01_3_DEATHS_SINGLE_AGE_FEMALE.xlsx

#Estimates sheet 1950-2023
# Medium variant 2024 -2050


# Visualize in ggplot 2 and place in output/ folder

# 1
# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex

# cause specific mortality rates (cvd) 2017-2050 vs gbd 1990-2023 by sex

# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
# 2020, 2030, 2040, 2050

# Cause specific mortality rate (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
# 2020, 2030, 2040, 2050

# total death counts (cvd+ background) 2017-2050 vs gbd 1990-2023

# total mortality rates (cvd+ background) 2017-2050 vs gbd 1990-2023

# 2 

# all cause death counts (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050

# all cause mortality rates (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050

# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years

# cause specific mortality rate (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years

