# This script perform validation analysis comparting mortality cases and rates (not standarized)
# To bechnmark sources by sex for ages 20+

# wd_outp, wd_raw and the packages below are assumed to be set up upstream
# (00_run_model_indonesia.R). Loaded here as well so the script is self-contained.
library(data.table)
library(ggplot2)
library(readxl)

# Model outputs

# Generated by 06_run_scenarios.R (parallel execution for Indonesia)
out_model_path <- paste0(wd_outp, "out_model/")
files <- list.files(path = out_model_path, pattern = "\\.rds$", full.names = TRUE)

data.out <- rbindlist(
  lapply(files, function(f) { dt <- readRDS(f); setDT(dt); dt }),
  use.names = TRUE, fill = TRUE
)
data.out <- data.out[!is.na(location)]

# Filter only business as usual scenario
data.out_bau <- data.out[intervention %in% c("baseline") & scenario %in% c("baseline"),]

# 1 Comparing model estimates 2017-2050 by cause vs gbd 1990-2023

# Gbd
dt_gbd  <- readRDS(file = paste0(wd_raw,"GBD/","temp_1baseline_rates_gbd23.rds"))
setDT(dt_gbd)

#2 All cause mortality (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050

# WPP2024 single-age deaths come in two sheets per file: "Estimates" (1950-2023)
# and "Medium variant" (2024-2050). The header sits on row 13, country is keyed on
# the ISO3 code, the Year column is followed by single-age columns 0..100+, and the
# values are deaths in thousands. read_wpp() returns a tidy long table for Indonesia.
read_wpp <- function(file, sheet){
  rawm <- as.matrix(as.data.frame(read_excel(file, sheet = sheet,
                                             col_names = FALSE, .name_repair = "minimal")))
  hrow <- which(apply(rawm, 1, function(r) any(r == "Year", na.rm = TRUE)))[1]
  hdr  <- rawm[hrow, ]
  ycol <- which(hdr == "Year")[1]
  icol <- which(hdr == "ISO3 Alpha-code")[1]
  acol <- (ycol + 1):ncol(rawm)
  ages <- as.numeric(sub("\\+", "", hdr[acol]))          # "100+" -> 100
  body <- rawm[(hrow + 1):nrow(rawm), , drop = FALSE]
  body <- body[!is.na(body[, icol]) & body[, icol] == "IDN", , drop = FALSE]
  n    <- nrow(body)
  data.table(
    year   = rep(as.numeric(body[, ycol]), times = length(acol)),
    age    = rep(ages, each = n),
    deaths = as.numeric(body[, acol]) * 1000             # thousands -> deaths
  )
}

#Estimates sheet 1950-2023
# Medium variant 2024 -2050
dt_unwpp_male <- rbind(
  read_wpp(paste0(wd_raw, "unwpp/WPP2024_MORT_F01_2_DEATHS_SINGLE_AGE_MALE.xlsx"), "Estimates")[year <= 2023],
  read_wpp(paste0(wd_raw, "unwpp/WPP2024_MORT_F01_2_DEATHS_SINGLE_AGE_MALE.xlsx"), "Medium variant")[year >= 2024]
)[, sex := "Male"]

dt_unwpp_female <- rbind(
  read_wpp(paste0(wd_raw, "unwpp/WPP2024_MORT_F01_3_DEATHS_SINGLE_AGE_FEMALE.xlsx"), "Estimates")[year <= 2023],
  read_wpp(paste0(wd_raw, "unwpp/WPP2024_MORT_F01_3_DEATHS_SINGLE_AGE_FEMALE.xlsx"), "Medium variant")[year >= 2024]
)[, sex := "Female"]

dt_unwpp <- rbind(dt_unwpp_male, dt_unwpp_female)
dt_unwpp <- dt_unwpp[year >= 1990 & year <= 2050 & age >= 20]

#...........................................................
# Data preparation (ages 20+, non-standardized) ----
#...........................................................

# 5-year age-group labels shared by every age-specific plot
age_levels <- c(paste0(seq(20, 90, 5), "-", seq(24, 94, 5)), "95+")
age_to_grp <- function(a){
  ub <- pmin(floor(a / 5) * 5, 95)
  ifelse(ub >= 95, "95+", paste0(ub, "-", ub + 4))
}

# GBD cause names that map to the six modelled CVD causes (ihd, istroke, hstroke,
# hhd, rhd, cmd). "All causes" and dementia are excluded from the CVD aggregate.
cvd6_gbd <- c("Ischemic heart disease", "Ischemic stroke", "Intracerebral hemorrhage",
              "Hypertensive heart disease", "Rheumatic heart disease",
              "Cardiomyopathy and myocarditis")

## Model -----------------------------------------------------------------
# `dead` is cause-specific; `pop` and `all.mx` (all-cause deaths) are stored per row
# but are constant across cause. mean() collapses any duplicate baseline rows that
# would arise if several htn_target_scenario files are present in out_model/.
m0 <- data.out_bau[age >= 20, .(dead = mean(dead), pop = mean(pop), all.mx = mean(all.mx)),
                   by = .(sex, age, year, cause)]
m_age <- m0[, .(cvd_deaths = sum(dead), pop = pop[1], all_deaths = all.mx[1]),
            by = .(sex, age, year)]
m_age[, age_grp := age_to_grp(age)]

m_trend <- m_age[, .(cvd_deaths = sum(cvd_deaths), all_deaths = sum(all_deaths), pop = sum(pop)),
                 by = .(sex, year)]
m_trend[, `:=`(cvd_rate = cvd_deaths / pop * 1e5, all_rate = all_deaths / pop * 1e5)]

m_grp <- m_age[, .(cvd_deaths = sum(cvd_deaths), pop = sum(pop)), by = .(sex, age_grp, year)]
m_grp[, cvd_rate := cvd_deaths / pop * 1e5]

## GBD -------------------------------------------------------------------
# Deaths come as both Number and Rate; population is recovered as Number / Rate * 1e5
# from the All-causes rows (the denominator is the same for every cause).
gd <- dt_gbd[measure_name == "Deaths" & sex_name %in% c("Male", "Female")]
gd[, age_grp := ifelse(age_name == "95+ years", "95+", sub(" years", "", age_name))]
gw <- dcast(gd, sex_name + age_grp + cause_name + year ~ metric_name, value.var = "val")
setnames(gw, "sex_name", "sex")

g_pop_age <- gw[cause_name == "All causes", .(sex, age_grp, year, pop = Number / Rate * 1e5)]
g_all_age <- gw[cause_name == "All causes", .(sex, age_grp, year, deaths = Number)]
g_cvd_age <- gw[cause_name %in% cvd6_gbd, .(cvd_deaths = sum(Number)), by = .(sex, age_grp, year)]

g_pop_tr <- g_pop_age[, .(pop = sum(pop)), by = .(sex, year)]
g_cvd_tr <- merge(g_cvd_age[, .(cvd_deaths = sum(cvd_deaths)), by = .(sex, year)],
                  g_pop_tr, by = c("sex", "year"))
g_cvd_tr[, cvd_rate := cvd_deaths / pop * 1e5]
g_all_tr <- merge(g_all_age[, .(all_deaths = sum(deaths)), by = .(sex, year)],
                  g_pop_tr, by = c("sex", "year"))
g_all_tr[, all_rate := all_deaths / pop * 1e5]

g_cvd_grp <- merge(g_cvd_age, g_pop_age, by = c("sex", "age_grp", "year"))
g_cvd_grp[, cvd_rate := cvd_deaths / pop * 1e5]

## UNWPP -----------------------------------------------------------------
# WPP supplies deaths only. For the crude rate the denominator is the GBD-implied
# population over 1990-2023 spliced with the IHME population for 2024-2050, giving a
# continuous Indonesia 20+ population that is independent of the model.
ihme    <- as.data.table(readRDS(paste0(wd_raw, "GBD/totalpop_ihme.rds")))
ihme_tr <- ihme[age_group >= 20, .(pop = sum(val)), by = .(sex = sex_name, year = year_id)]
pop_unwpp <- rbind(g_pop_tr[year <= 2023], ihme_tr[year >= 2024 & year <= 2050])

u_all_tr <- dt_unwpp[, .(all_deaths = sum(deaths)), by = .(sex, year)]
u_all_tr <- merge(u_all_tr, pop_unwpp, by = c("sex", "year"))
u_all_tr[, all_rate := all_deaths / pop * 1e5]

#...........................................................
# Plot helpers (consistent source colour / linetype) ----
#...........................................................

source_levels    <- c("Model", "GBD", "UNWPP")
source_colors    <- c(Model = "#E41A1C", GBD = "#377EB8", UNWPP = "#4DAF4A")
source_linetypes <- c(Model = "solid",   GBD = "dashed", UNWPP = "dotted")

as_source <- function(x) factor(x, levels = source_levels)

# Year-trend plot: one line per source, faceted by sex
plot_trend <- function(dat, ytitle, title){
  ggplot(dat, aes(year, value, colour = source, linetype = source)) +
    geom_line(linewidth = 0.9) +
    facet_wrap(~ sex, scales = "free_y") +
    scale_colour_manual(values = source_colors, limits = source_levels) +
    scale_linetype_manual(values = source_linetypes, limits = source_levels) +
    labs(x = "Year", y = ytitle, colour = "Source", linetype = "Source", title = title) +
    theme_bw(base_size = 12)
}

# Age-profile plot: value over 5-year age groups, faceted by sex x year
plot_age <- function(dat, ytitle, title){
  ggplot(dat, aes(age_grp, value, colour = source, linetype = source, group = source)) +
    geom_line(linewidth = 0.8) +
    geom_point(size = 1.2) +
    facet_grid(sex ~ year, scales = "free_y") +
    scale_colour_manual(values = source_colors, limits = source_levels) +
    scale_linetype_manual(values = source_linetypes, limits = source_levels) +
    labs(x = "Age group", y = ytitle, colour = "Source", linetype = "Source", title = title) +
    theme_bw(base_size = 11) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
}

# Visualize in ggplot 2 and place in output/ folder
dir.create(wd_outp, showWarnings = FALSE, recursive = TRUE)
save_plot <- function(p, name, width = 9, height = 5){
  ggsave(filename = paste0(wd_outp, name), plot = p, width = width, height = height, dpi = 150)
}

# 1
# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex
d_cvd_deaths <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = cvd_deaths)],
  g_cvd_tr[, .(source = as_source("GBD"),   sex, year, value = cvd_deaths)]
)
save_plot(
  plot_trend(d_cvd_deaths, "CVD deaths (count, ages 20+)",
             "CVD deaths: Model (2017-2050) vs GBD (1990-2023)"),
  "09_validation_cvd_deaths_trend_by_sex.png"
)

# cause specific mortality rates (cvd) 2017-2050 vs gbd 1990-2023 by sex
d_cvd_rate <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = cvd_rate)],
  g_cvd_tr[, .(source = as_source("GBD"),   sex, year, value = cvd_rate)]
)
save_plot(
  plot_trend(d_cvd_rate, "CVD mortality rate (per 100,000, ages 20+)",
             "CVD mortality rate: Model (2017-2050) vs GBD (1990-2023)"),
  "09_validation_cvd_rate_trend_by_sex.png"
)

# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
# 2020, 2030, 2040, 2050
yrs_proj <- c(2020, 2030, 2040, 2050)
d_cvd_deaths_age <- rbind(
  m_grp[year %in% yrs_proj,     .(source = as_source("Model"), sex, age_grp, year, value = cvd_deaths)],
  g_cvd_grp[year %in% yrs_proj, .(source = as_source("GBD"),   sex, age_grp, year, value = cvd_deaths)]
)
d_cvd_deaths_age[, age_grp := factor(age_grp, levels = age_levels)]
save_plot(
  plot_age(d_cvd_deaths_age, "CVD deaths (count, ages 20+)",
           "CVD deaths by age group: Model vs GBD"),
  "09_validation_cvd_deaths_by_agegroup.png", width = 11, height = 6
)

# Cause specific mortality rate (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
# 2020, 2030, 2040, 2050
d_cvd_rate_age <- rbind(
  m_grp[year %in% yrs_proj,     .(source = as_source("Model"), sex, age_grp, year, value = cvd_rate)],
  g_cvd_grp[year %in% yrs_proj, .(source = as_source("GBD"),   sex, age_grp, year, value = cvd_rate)]
)
d_cvd_rate_age[, age_grp := factor(age_grp, levels = age_levels)]
save_plot(
  plot_age(d_cvd_rate_age, "CVD mortality rate (per 100,000, ages 20+)",
           "CVD mortality rate by age group: Model vs GBD"),
  "09_validation_cvd_rate_by_agegroup.png", width = 11, height = 6
)

# total death counts (cvd+ background) 2017-2050 vs gbd 1990-2023
d_all_deaths <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = all_deaths)],
  g_all_tr[, .(source = as_source("GBD"),   sex, year, value = all_deaths)]
)
save_plot(
  plot_trend(d_all_deaths, "All-cause deaths (count, ages 20+)",
             "All-cause deaths (CVD + background): Model vs GBD"),
  "09_validation_allcause_deaths_trend.png"
)

# total mortality rates (cvd+ background) 2017-2050 vs gbd 1990-2023
d_all_rate <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = all_rate)],
  g_all_tr[, .(source = as_source("GBD"),   sex, year, value = all_rate)]
)
save_plot(
  plot_trend(d_all_rate, "All-cause mortality rate (per 100,000, ages 20+)",
             "All-cause mortality rate (CVD + background): Model vs GBD"),
  "09_validation_allcause_rate_trend.png"
)

# 2

# all cause death counts (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050
d_all_deaths_u <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = all_deaths)],
  g_all_tr[, .(source = as_source("GBD"),   sex, year, value = all_deaths)],
  u_all_tr[, .(source = as_source("UNWPP"), sex, year, value = all_deaths)]
)
save_plot(
  plot_trend(d_all_deaths_u, "All-cause deaths (count, ages 20+)",
             "All-cause deaths: Model vs GBD vs UNWPP"),
  "09_validation_allcause_deaths_trend_with_unwpp.png"
)

# all cause mortality rates (cvd+ background) 2017-2050 vs gbd 1990-2023 and UNWPP 1990-2050
d_all_rate_u <- rbind(
  m_trend[,  .(source = as_source("Model"), sex, year, value = all_rate)],
  g_all_tr[, .(source = as_source("GBD"),   sex, year, value = all_rate)],
  u_all_tr[, .(source = as_source("UNWPP"), sex, year, value = all_rate)]
)
save_plot(
  plot_trend(d_all_rate_u, "All-cause mortality rate (per 100,000, ages 20+)",
             "All-cause mortality rate: Model vs GBD vs UNWPP"),
  "09_validation_allcause_rate_trend_with_unwpp.png"
)

# Cause specific total death counts (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
yrs_dec <- c(1990, 2000, 2010, 2020, 2030, 2040, 2050)
d_cvd_deaths_dec <- rbind(
  m_grp[year %in% yrs_dec,     .(source = as_source("Model"), sex, age_grp, year, value = cvd_deaths)],
  g_cvd_grp[year %in% yrs_dec, .(source = as_source("GBD"),   sex, age_grp, year, value = cvd_deaths)]
)
d_cvd_deaths_dec[, age_grp := factor(age_grp, levels = age_levels)]
save_plot(
  plot_age(d_cvd_deaths_dec, "CVD deaths (count, ages 20+)",
           "CVD deaths by age group (every 10 years): Model vs GBD"),
  "09_validation_cvd_deaths_by_agegroup_decadal.png", width = 14, height = 6
)

# cause specific mortality rate (cvd) 2017-2050 vs gbd 1990-2023 by sex and 5 years age group every 10 years
d_cvd_rate_dec <- rbind(
  m_grp[year %in% yrs_dec,     .(source = as_source("Model"), sex, age_grp, year, value = cvd_rate)],
  g_cvd_grp[year %in% yrs_dec, .(source = as_source("GBD"),   sex, age_grp, year, value = cvd_rate)]
)
d_cvd_rate_dec[, age_grp := factor(age_grp, levels = age_levels)]
save_plot(
  plot_age(d_cvd_rate_dec, "CVD mortality rate (per 100,000, ages 20+)",
           "CVD mortality rate by age group (every 10 years): Model vs GBD"),
  "09_validation_cvd_rate_by_agegroup_decadal.png", width = 14, height = 6
)
